### ISSUE TITLE
Argument labels '(String:)' do not match any available overloads

### ISSUE THREAD

**Issue by urvishshah17** [urvishshah17/Weather_alamofire#1]
Trying to use this code.
<img width="687" alt="screen shot 2017-12-19 at 11 12 31 pm" src="https://user-images.githubusercontent.com/29333741/34191183-0c605de0-e513-11e7-97db-018d877fec74.png">
I get the error "Argument labels '(String:)' do not match any available overloads"
Any ideas how I can fix this?

**Comment by akuzminskyi** [comment]
@urvishshah17 Hi. You should use lowercase in argument label of URL, "string" instead of "String". I've sent a pull request #2 with changes.
